services:
  dashboard:
    platform: linux/amd64
    image: geocompas/geosam-service
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
      - ./module:/home/jovyan/.cache/torch/hub/checkpoints
    ports:
      - '8000:8000'
