services:
  samgeo:
    platform: linux/amd64
    image: geocompas/samgeo-service
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
      - ./module:/home/jovyan/.cache/torch/hub/checkpoints
    ports:
      - '80:80'
